name: Thank you
on:
  pull_request:
    types:
      - opened
    paths:
      - "website/**"
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            Thank you for your contribution @${{ github.event.pull_request.user.login }} :blue_heart:
            
            We will review your PR soon.
          repo-token: ${{ secrets.MAINTAINER_PAT }}
