name: Trigger deploy on comment
on:
  issue_comment:
    types: [created]
jobs:
  if_merged:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest
    steps:
      - name: User has permission to deploy
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            // Check if the user trying to deploy is an authorized user
            const creator = context.payload.sender.login
            const authorizedHandles = ["mvkaran", "abhinavrajesh"]
            if(!authorizedHandles.includes(creator.toLowerCase())) {
              core.setFailed("User not authorized to deploy")
            }
      - name: Trigger build
        uses: benc-uk/workflow-dispatch@d004979be141727c7a17c28f603e2facc40d0855 # v1.3.3
        with:
          repo: ${{ secrets.GITHUBINDIA_REPO_NWO }}
          workflow: Trigger build when public PR is merged
          token: ${{ secrets.PAT }}
          inputs: '{"pr_number": "${{ github.event.issue.number }}", "creator_username": "${{ github.event.issue.user.login  }}" }'
